### ISSUE TITLE
Create HP and damage system

### ISSUE THREAD

**Issue by Remi-Godin** [ASU-CodeDevils/CD-GameDev#1]
The player will need HP and can take damage, as will any other NPC or enemies.
 
Requirements:
- Create necessary components to give things HP
- Create necessary components to take away HP from an entity
- Must be able to query for `Dead` entities

**Comment by andresvanegas19** [comment]
Would be good if you can have a little more detail description of "What's the game about"

**Comment by Remi-Godin** [comment]
@andresvanegas19 Are you a student at ASU? This project was created for the CodeDevils organization's members. Right now, we just created the scaffolding for the project, but the details and vision will be determined as we progress. This is why currently things are pretty generic in regard to issues. If you are part of our club, please reach out to me on our Discord and I'll add you to the project channel.

**Comment by Remi-Godin** [comment]
@andresvanegas19 I appreciate your enthusiasm, but unfortunately, at this point anyway, we want to keep contributions from within our member body only. 

You should join the [Bevy Discord](https://discord.com/invite/bevy). I'm sure there are many in there looking for help on their project, and it's generally just a great community for Rust game development.

**Comment by joshuawalker3** [comment]
I'll get started on this.
