### ISSUE TITLE
Create animation system

### ISSUE THREAD

**Issue by Remi-Godin** [ASU-CodeDevils/CD-GameDev#2]
Create a Bevy plugin to facilitate handling animations from sprite sheets. Most sprite sheets contain multiple animations, and we should be able to play each of them whenever we want, and even mix and match frames to create new ones if possible. Once an animation is defined, it should be saved in a collection of sort that we can then go through and select which one to play at any given time.

 See [this example](https://bevyengine.org/examples/2d-rendering/sprite-sheet/) from the official Bevy examples to see how sprite animation works. In the example, you can see that the texture atlas (or sprite sheet) is broken down into a [`TextureAtlasLayout`](https://docs.rs/bevy/latest/bevy/sprite/struct.TextureAtlasLayout.html), which is saved in the asset server. On the character, there is a [`TextureAtlas`](https://docs.rs/bevy/latest/bevy/prelude/struct.TextureAtlas.html) component that references that [`TextureAtlasLayout`](https://docs.rs/bevy/latest/bevy/sprite/struct.TextureAtlasLayout.html). In the `animate_sprite` system, we query the [`TextureAtlas`](https://docs.rs/bevy/latest/bevy/prelude/struct.TextureAtlas.html) component and the index is changed every time the timer has completed a cycle.

The goal here would be to have a component we can add to our sprites which will play the selected animation continuously, at the desired speed. Animation selection would be driven by external events outside this plugin.

Requirements:
- Should be able to extract multiple animations from a sprite sheet and save them with different names
- Should be able to select a range of frames to be part of each animation (frame range might not be consecutive)
- frame time should be able to be controlled, in the event we want to speed up or slow down an animation
- We should be able to select which animation to play at any given time

Stretch goals:
- Have the option for single cycle animations
- Have the option for mirroring animations

**Comment by 4pt1y** [comment]
Hey bossman, I'd love to give this a shot.

**Comment by Remi-Godin** [comment]
You got it :sunglasses:

**Comment by 4pt1y** [comment]
Thanks! I'm scared and excited. :D

**Comment by 4pt1y** [comment]
Removed myself as assignee on the issue...sorry everything, I am out of my depth on this one. I'll absolutely hop on another issue in the future but I just need to learn more about Rust/Bevy first.
